[tool.poetry]
name = "treegnore"
version = "0.1.0"
description = ""
authors = ["Harutyun <harutyun.ag.petr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
